<a href="https://colab.research.google.com/github/SunWoo-PARK/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [9]:
def phasor(amp, sr, dur, freq):
    time = np.arange(1, sr*dur*1)/sr;
    theta = time * 2*np.pi * freq;
    s = np.sin(theta);
    return s, theta, time

In [10]:
phasor(1, 10000, 0.5, 100)

(array([ 0.06279052,  0.12533323,  0.18738131, ..., -0.18738131,
        -0.12533323, -0.06279052]),
 array([6.28318531e-02, 1.25663706e-01, 1.88495559e-01, ...,
        3.13970770e+02, 3.14033602e+02, 3.14096434e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.997e-01, 4.998e-01,
        4.999e-01]))